export type SIconType =
  | 'SIconChevronDown'
  | 'SIconLoading'
  | 'SIconCameraOutline'
  | 'SIconFileMultipleOutline'
  | 'SIconFileOutline'
  | 'SIconVectorDifferenceBa'
  | 'SIconClose'
  | 'SIconCloseCircle'
  | 'SIconImageArea'
  | 'SIconMovieOutline'
