export type MaterialDesignIcon = string

export type MaterialDesignIconExtra =
  | 'mdi-18px'
  | 'mdi-24px'
  | 'mdi-36px'
  | 'mdi-48px'
  | 'mdi-36px'
  | 'mdi-rotate-45'
  | 'mdi-rotate-90'
  | 'mdi-rotate-135'
  | 'mdi-rotate-180'
  | 'mdi-rotate-225'
  | 'mdi-rotate-270'
  | 'mdi-rotate-315'
  | 'mdi-flip-h'
  | 'mdi-flip-v'
  | 'mdi-spin'
  | 'mdi-inactive'
  | 'mdi-light'
  | 'mdi-dark '
