import { faker } from '@khsura/shared'
import type { TableHeader, TableItem } from '@khsura/sui/types'

export const tableHeaders: TableHeader[] = [
  {
    text: 'no',
    value: 'number',
    width: '20',
    align: 'center',
    textWrap: true,
    sortable: true,
    cellNoGutters: true,
  },
  { text: 'header2', value: 'value2', width: '150', align: 'start' },
  {
    text: 'header3',
    align: 'center',
    sortable: true,
    value: 'value3',
    width: '30%',
    cellClass: 's_text--truncate',
  },
  {
    text: 'header4',
    value: 'value4',
    sortable: true,
    width: '20%',
  },
  { text: 'header5', value: 'value5', align: 'end', width: '10%' },
  { text: 'header6', value: 'value6', align: 'center', width: '10%', sortable: true },
  { text: 'header7', value: 'value7', width: '10%' },
  { text: 'header8', value: 'value8', width: '300px' },
]

export const tableItems: TableItem[] = [
  {
    number: 1,
    value2: faker.animal.type(),
    value3: 'Frozen Yogurt',
    value4: 159,
    value5: 6.0,
    value6: 24,
    value7: 4.0,
    value8: '1%',
  },
  {
    number: 2,
    value2: faker.animal.type(),
    value3: 'Ice cream sandwich',
    value4: 237,
    value5: 9.0,
    value6: 37,
    value7: 4.3,
    value8: '1%',
  },
  {
    number: 3,
    value2: faker.animal.type(),
    value3: 'Eclair',
    value4: 262,
    value5: 16.0,
    value6: 23,
    value7: 6.0,
    value8: '7%',
  },
  {
    number: 4,
    value3: 'Cupcake',
    value2: faker.animal.type(),
    value4: 305,
    value5: 3.7,
    value6: 67,
    value7: '-',
    value8: '8%',
  },
  {
    number: 5,
    value3: 'Gingerbread',
    value2: faker.animal.type(),
    value4: 356,
    value5: 16.0,
    value6: 49,
    value7: 3.9,
    value8: '16%',
    footerMessage: 'Gingerbread is very delicious',
  },
  {
    number: 6,
    value3: 'Jelly bean',
    value2: faker.animal.type(),
    value4: 375,
    value5: 0.0,
    value6: 94,
    value7: 0.0,
    value8: '0%',
  },
  {
    number: 7,
    value3: 'Lollipop',
    value2: faker.animal.type(),
    value4: 392,
    value6: 0.2,
    value7: 98,
    value8: '-',
    value9: '2%',
  },
  {
    number: 8,
    value3: 'Honeycomb',
    value2: faker.animal.type(),
    value4: 408,
    value5: 3.2,
    value6: 87,
    value7: 6.5,
    value8: '45%',
  },
  {
    number: 9,
    value3: 'Donut',
    value2: faker.animal.type(),
    value4: 452,
    value6: 25.0,
    value7: 51,
    value8: 4.9,
    value9: '22%',
  },
  {
    number: 10,
    value3: 'KitKat',
    value2: faker.animal.type(),
    value4: 518,
    value6: 26.0,
    value7: 65,
    value8: 7,
    value9: '6%',
    footerMessage: 'KitKat is very delicious',
  },
  {
    number: 11,
    value3: 'KitKat',
    value2: faker.animal.type(),
    value4: 518,
    value6: 26.0,
    value7: 65,
    value8: 7,
  },
]
