checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: $NPM_GITHUB_TOKEN
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: $NPM_TOKEN

npmScopes:
  sui:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
