// TODO: remove. use hard coded name instead
export enum ComponentBlockName {
  app = 'app',
  appBar = 'appBar',
  button = 'button',
  icon = 'icon',
  image = 'image',
  progress = 'progress',
  container = 'container',
  row = 'row',
  column = 'column',
  tabs = 'tabs',
  tab = 'tab',
  form = 'form',
  input = 'input',
  select = 'select',
  subheader = 'subheader',
  switch = 'switch',
  radio = 'radio',
  radioGroup = 'radioGroup',
  menu = 'menu',
  table = 'table',
  chip = 'chip',
}
