export enum ProviderName {
  sui = 'suiProvider',
  form = 'form',
  stepperRegisterStepperStep = 'stepperRegisterStepperStep',
  stepperSteps = 'stepperSteps',
  stepperUnregisterStepperStep = 'stepperUnregisterStepperStep',
  stepperUpdateValue = 'stepperUpdateValue',
  group = 'groupProvider',
  singleGroup = 'singleGroupProvider',
  app = 'appProvider',
  expansionPanel = 'expanstionPanelProvider',
}

export enum ProviderPropsName {
  radioGroupProps = 'radioGroupProps',
  stepperProps = 'stepperProps',
  tabsProps = 'tabsProps',
  listProps = 'listProps',
  listItemProps = 'listItemProps',
  toggleButtonGroupProps = 'toggleButtonGroupProps',
  groupProps = 'groupProps',
  groupSingleProps = 'groupSingleProps',
  slideGroupProps = 'slideGroupProps',
  navigationDrawerProps = 'navigationDrawerProps',
  bottomNavigation = 'bottomNavigationProps',
  toolbar = 'toolbarProps',
  window = 'windowProps',
  splitViewProps = 'splitViewProps',
  expansionPanelsProps = 'expansionPanelProps',
}
