name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  HUSKY: 0

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Debug release output
        run: |
          echo "Release Created: $RELEASE_CREATED"
        env:
          RELEASE_CREATED: ${{ steps.release.outputs.release_created }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        if: ${{ steps.release.outputs.release_created }}

      - name: Enable Corepack
        run: corepack enable
        if: ${{ steps.release.outputs.release_created }}

      - name: Set token npm github token
        run: echo NPM_GITHUB_TOKEN=${{ secrets.NPM_GITHUB_TOKEN }} > .env.yarn
        if: ${{ steps.release.outputs.release_created }}

      - name: Set yarn version
        run: yarn set version self
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: yarn install
        if: ${{ steps.release.outputs.release_created }}

      - name: Run publish
        run: yarn release
        if: ${{ steps.release.outputs.release_created }}
