name: Test & Build

on:
  pull_request:
    branches:
      - main
env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Set token npm github token
        run: echo NPM_GITHUB_TOKEN=${{ secrets.NPM_GITHUB_TOKEN }} > .env.yarn

      - name: Set yarn version
        run: yarn set version self

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build
